spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_alertas
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082
